on:
  push:

jobs:
  main:
    name: Github container registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          # registry: docker.pkg.github.com
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker build & push
        uses: docker/build-push-action@v2.3.0
        with:
          tags: ghcr.io/htdangkhoa/base_node:latest
          push: true
