# This is a basic workflow to help you get started with Actions

name: trigger

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  TEST: "1111"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: github.ref
    
    - name: Get current package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.1.0
      
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
      
    - run: |
        echo hello world ${{ env.TEST }} ${{ steps.package-version.outputs.current-version }}
        echo Branch: ${{ github.ref }}

