# This is a basic workflow to help you get started with Actions

name: trigger

on: 
  workflow_dispatch:

env:
  TEST: "1111"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get current package version
      uses: martinbeentjes/npm-get-version-action@v1.1.0
      
    - run: |
        echo hello world ${{ env.TEST }} ${{ steps.package-version.outputs.current-version }}

