# This is a basic workflow to help you get started with Actions

name: trigger

on: 
  workflow_dispatch:

env:
  TEST: "1111"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hello world ${{ env.TEST }}

