# This is a basic workflow to help you get started with Actions

name: trigger

on: 
  workflow_dispatch:

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello world"

