# This is a basic workflow to help you get started with Actions

name: trigger

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  TEST: "1111"

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo GITHUB_SHA:$GITHUB_SHA
        echo GITHUB_REF:$GITHUB_REF

    - run: |
        git pull
        
        git checkout $GITHUB_SHA

